development:
  adapter:  postgresql
  database: testdrive_dev
  pool:     5
  timeout:  5000
  host:     localhost

test:
  adapter:  postgresql
  database: testdrive_test
  pool:     5
  timeout:  5000
  host:     localhost

production:
  adapter:  postgresql
  database: testdrive_prod
  pool:     5
  timeout:  5000
  host:     localhost
